#!/bin/bash
# Configure SSH for easy access to NeuROAM payloads
# This script sets up ~/.ssh/config with aliases for payload0-5
# and includes GitHub configuration

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SSH_CONFIG_FILE="$HOME/.ssh/config"
BACKUP_SUFFIX=".backup.$(date +%Y%m%d_%H%M%S)"
USERNAME="${1:-neuroam}"  # Default username, can be overridden

# Payload IP addresses
declare -A PAYLOAD_IPS=(
    [0]="10.19.30.100"
    [1]="10.19.30.101"
    [2]="10.19.30.102"
    [3]="10.19.30.103"
    [4]="10.19.30.104"
    [5]="10.19.30.105"  # Added payload5 for future expansion
)

echo -e "${BLUE}======================================${NC}"
echo -e "${BLUE}NeuROAM SSH Configuration Script${NC}"
echo -e "${BLUE}======================================${NC}"
echo ""

# Create ~/.ssh directory if it doesn't exist
if [ ! -d "$HOME/.ssh" ]; then
    echo -e "${YELLOW}Creating ~/.ssh directory...${NC}"
    mkdir -p "$HOME/.ssh"
    chmod 700 "$HOME/.ssh"
fi

# Backup existing config if it exists
if [ -f "$SSH_CONFIG_FILE" ]; then
    echo -e "${YELLOW}Backing up existing SSH config to:${NC}"
    echo -e "  $SSH_CONFIG_FILE$BACKUP_SUFFIX"
    cp "$SSH_CONFIG_FILE" "$SSH_CONFIG_FILE$BACKUP_SUFFIX"
fi

# Generate the SSH config content
echo -e "${GREEN}Generating SSH configuration...${NC}"

cat > "$SSH_CONFIG_FILE" << 'EOF'
# NeuROAM SSH Configuration
# Generated by config_ssh.sh

# GitHub configuration
Host github.com
  HostName github.com
  User git
  GSSAPIAuthentication no
  PreferredAuthentications publickey
  IdentitiesOnly yes

EOF

# Add payload configurations
for payload_id in {0..5}; do
    ip="${PAYLOAD_IPS[$payload_id]}"
    cat >> "$SSH_CONFIG_FILE" << EOF
# Payload $payload_id
Host payload$payload_id
  HostName $ip
  User $USERNAME
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  ServerAliveInterval 60
  ServerAliveCountMax 3
  ConnectTimeout 5

EOF
done

# Add a catch-all for all payloads (useful for scripts)
cat >> "$SSH_CONFIG_FILE" << EOF
# Catch-all for payload IPs (10.19.30.100-105)
Host 10.19.30.10?
  User $USERNAME
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  ServerAliveInterval 60
  ServerAliveCountMax 3
  ConnectTimeout 5
EOF

# Set correct permissions
chmod 600 "$SSH_CONFIG_FILE"

echo -e "${GREEN}✓ SSH configuration created successfully!${NC}"
echo ""
echo -e "${BLUE}Configuration summary:${NC}"
echo -e "  • SSH config file: $SSH_CONFIG_FILE"
echo -e "  • Username: $USERNAME"
echo -e "  • GitHub configured for git access"
echo ""
echo -e "${BLUE}Available payload aliases:${NC}"
for payload_id in {0..5}; do
    ip="${PAYLOAD_IPS[$payload_id]}"
    echo -e "  ${GREEN}payload$payload_id${NC} → $ip"
done
echo ""
echo -e "${BLUE}Usage examples:${NC}"
echo -e "  ${YELLOW}ssh payload0${NC}                 # Connect to payload 0 (10.19.30.100)"
echo -e "  ${YELLOW}ssh payload1${NC}                 # Connect to payload 1 (10.19.30.101)"
echo -e "  ${YELLOW}ssh payload2 'hostname'${NC}      # Run command on payload 2"
echo -e "  ${YELLOW}scp file.txt payload3:~/${NC}     # Copy file to payload 3"
echo -e "  ${YELLOW}ssh 10.19.30.104${NC}             # Direct IP also uses config"
echo ""
echo -e "${BLUE}Testing connectivity...${NC}"

# Test connectivity to each payload
success_count=0
fail_count=0

for payload_id in {0..4}; do  # Test 0-4 by default (5 may not exist yet)
    ip="${PAYLOAD_IPS[$payload_id]}"
    echo -n "  Testing payload$payload_id ($ip)... "
    
    if timeout 2 ssh -o BatchMode=yes -o ConnectTimeout=2 payload$payload_id echo "OK" &>/dev/null; then
        echo -e "${GREEN}✓ Connected${NC}"
        ((success_count++))
    else
        # Try with password authentication (sshpass)
        if command -v sshpass &>/dev/null; then
            if timeout 2 sshpass -p "$USERNAME" ssh -o ConnectTimeout=2 payload$payload_id echo "OK" &>/dev/null 2>&1; then
                echo -e "${YELLOW}✓ Connected (password auth)${NC}"
                ((success_count++))
            else
                echo -e "${RED}✗ Failed${NC}"
                ((fail_count++))
            fi
        else
            echo -e "${YELLOW}? Unknown (install sshpass for password auth)${NC}"
            ((fail_count++))
        fi
    fi
done

echo ""
if [ $success_count -gt 0 ]; then
    echo -e "${GREEN}✓ Successfully connected to $success_count payload(s)${NC}"
fi

if [ $fail_count -gt 0 ]; then
    echo -e "${YELLOW}⚠️  Could not connect to $fail_count payload(s)${NC}"
    echo -e "${YELLOW}   Possible reasons:${NC}"
    echo -e "   • Payloads may be powered off or not reachable"
    echo -e "   • SSH keys may not be set up (use password authentication)"
    echo -e "   • Network configuration issues"
    echo ""
    echo -e "${BLUE}To set up SSH keys for passwordless access:${NC}"
    echo -e "   1. Generate key if needed: ${YELLOW}ssh-keygen -t ed25519${NC}"
    echo -e "   2. Copy to payloads: ${YELLOW}ssh-copy-id payload0${NC}"
    echo -e "   3. Or use password: ${YELLOW}sshpass -p '$USERNAME' ssh payload0${NC}"
fi

echo ""
echo -e "${GREEN}Configuration complete!${NC}"
