ros2 bag record -o full_capture_$(date +%Y-%m-%d-%H-%M-%S) -s mcap --max-bag-duration 600 \
  /parameter_events \
  /rosout \
  /ouster/os_driver/transition_event \
  /ouster/metadata \
  /ouster/imu \
  /ouster/points \
  /ouster/telemetry \
  /vectornav/raw/common \
  /vectornav/raw/time \
  /vectornav/raw/imu \
  /vectornav/raw/gps \
  /vectornav/raw/attitude \
  /vectornav/raw/ins \
  /vectornav/raw/gps2 \
  /vectornav/time_startup \
  /vectornav/time_gps \
  /vectornav/time_syncin \
  /vectornav/time_pps \
  /vectornav/imu \
  /vectornav/gnss \
  /vectornav/imu_uncompensated \
  /vectornav/magnetic \
  /vectornav/velocity_aiding \
  /vectornav/temperature \
  /vectornav/pressure \
  /vectornav/velocity_body \
  /vectornav/pose \
  /ublox_gps_node/navpvt \
  /ublox_gps_node/fix \
  /ublox_gps_node/fix_velocity \
  /rtcm \
  /tf_static \
  /diagnostics \
  /navstatus \
  /navcov \
  /navclock \
  /aidalm \
  /aideph \
  /nmea \
  /navstate \
  /monhw \
  /rxmrtcm \
  /timtm2 \
  /interrupt_time \
  /rxmsfrb \
  /rxmraw \
  /cam_sync/cam0/meta \
  /cam_sync/cam0/image_raw \
  /cam_sync/cam0/camera_info \
  /cam_sync/cam1/meta \
  /cam_sync/cam1/image_raw \
  /cam_sync/cam1/camera_info \
  /doodle_monitor/activity \
  /doodle_monitor/iperf_result \
  /doodle_monitor/lna_status \
  /doodle_monitor/mesh_status \
  /doodle_monitor/noise \
  /doodle_monitor/peer_list \
  /doodle_monitor/ping_result \
  /doodle_monitor/raw \
  /doodle_monitor/sta_status \
  /doodle_monitor/sys/cpu_load \
  /doodle_monitor/sys/freemem \
  /doodle_monitor/sys/localtime

